const SUCCESS_MESSAGE = () => "OPERAÇÃO EXECUTADA COM SUCESSO.";
const ERROR_AUTORIZACAO = () => "VOCÊ NÃO TEM PERMISSÃO PARA GERENCIAR ESSE REGISTRO.";
const ERROR_MESSAGE = () => "OPS! OCORREU ALGUM ERROR.";
const ERROR_LOGIN = () => "OPS! CPF OU SENHA INVÁLIDO";
const ERROR_JWT = () => "OPS! TOKEN INVÁLIDO";

export { ERROR_MESSAGE, ERROR_AUTORIZACAO, SUCCESS_MESSAGE, ERROR_LOGIN, ERROR_JWT }