const SUCCESS_MESSAGE = () => "OPERAÇÃO EXECUTADA COM SUCESSO.";
const ERROR_AUTORIZACAO = () => "VOCÊ NÃO TEM PERMISSÃO PARA GERENCIAR ESSE REGISTRO.";
const ERROR_MESSAGE = () => "OPS! OCORREU ALGUM ERROR.";

export { ERROR_MESSAGE, ERROR_AUTORIZACAO, SUCCESS_MESSAGE }